app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewButtons.kt, app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCardViews.kt, app/src/main/java/kg/devcats/compose/samples/ui/extension/TestExtensions.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/buttons/ChiliCustomButton.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/buttons/ChiliPrimaryButton.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/cards/AlertBlockCardView.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/cards/InfoBlockCardView.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/Color.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/ColorScheme.kt, jetpack_chili/src/main/res/drawable/chili_ic_caution.xml, jetpack_chili/src/main/res/drawable/chili_ic_error.xml, jetpack_chili/src/main/res/drawable/chili_ic_information.xml
https://jira.devcats.kg/browse/OM-29461
=> OM-29461 -> InfoBlockCardView -> AlertBlockCardView

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCardViews.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/cards/ProductCardView.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/Color.kt
https://jira.devcats.kg/browse/OM-29500
=> OM-29500 -> added ProductCardView

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCommon.kt, app/src/main/res/values/strings.xml, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/common/AgreementCell.kt, jetpack_chili/src/main/res/drawable/chili_ic_checkmark.xml
added new common component for agreements https://jira.devcats.kg/browse/OM-29535
=> Om 29535 aggrement cell

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewDividers.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/ComposeExtensions.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/divider/Divider.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/divider/TitledDivider.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/divider/TitledDividerDefaults.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/divider/TitledDividerWithAction.kt, jetpack_chili/src/main/res/drawable/ic_shevron.xml
Task: https://jira.devcats.kg/browse/OM-29554
=> added start icon on divider and added display options

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCards.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/cards/StoriesCard.kt
https://jira.devcats.kg/browse/OM-29593
=> OM-29593 -> added StoriesCard

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCards.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/cards/PromoCard.kt
https://jira.devcats.kg/browse/OM-29603
=> OM-29603 -> added PromoCard

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewBottomSheets.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/modals/bottom_sheets/ChiliBottomSheetContainer.kt
https://jira.devcats.kg/browse/OM-29750
=> OM-29750 -> added functionality showFullScreen to BottomSheet

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/zoomablebox/PointerInputScopeExtensions.kt
Task: https://jira.devcats.kg/browse/OMD-11710
=> optimization zoom

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCommon.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/common/ChiliLinearProgressIndicator.kt
Task: https://jira.devcats.kg/browse/BONUS-1699
=> BONUS-1699(refactor): Added linear progress indicator

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/input_fields/ChiliPlainInputField.kt
https://jira.devcats.kg/browse/OM-30517
=> OM-30517 (fix): fix bug with focusing in InputFields

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/ColorPairScheme.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/ColorScheme.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/Theme.kt
Task: https://jira.devcats.kg/browse/BONUS-1730
=> BONUS-1730(feature): Added color scheme for banner buttons

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/input_fields/ChiliUneditableInputField.kt
https://jira.devcats.kg/browse/OM-30609
=> OM-30609 (feat): Added parameter for changing background color of ChiliUneditableInputField

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/ComposeExtensions.kt
=> OM-30567: single click extension

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/Color.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/ColorScheme.kt
https://jira.devcats.kg/browse/OM-30749
=> OM-30749 (style): added statusBg color

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/modals/snackbar/SnackbarManager.kt
- fix not showing new snackbar while old one is showing
- call onTimerExpire on scope completion
- call onTimerExpire on snackbar hidden
=> OM-30774 (feat): Deleting queue on new snackbar calling

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/input_fields/input_interceptors/MaskInputInterceptor.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/modals/snackbar/SnackbarManager.kt
- snackbar on onDismiss invokes 2 times OnCompletion
- make clearMaskSymbols public to get cleared text
=> (fix) fix_snackbar_&_make_public_clearMaskSymbols

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/ComposeExtensions.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/input_fields/ChiliInputField.kt
- message/error padding as parameter for ChiliInputField
=> (feat) add function to reset singleClick timer

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/pin_lock/PreviewCustomPinInput.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/keyboards/ActionButton.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/keyboards/PinKeyboard.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/ColorPairScheme.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/theme/ColorScheme.kt
Task: https://jira.devcats.kg/browse/OM-31103
=> OM-31103(refactor): added tunduk color scheme, and refactor pin screen

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCommon.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/util/compose_utils/showcase/SequenceShowcaseBox.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/util/compose_utils/showcase/ShowcaseHighlight.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/util/compose_utils/showcase/ShowcaseStep.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/util/compose_utils/showcase/state/SequenceShowcaseState.kt
Task: https://jira.devcats.kg/browse/MKK-11169
=> Mkk 11169 - Sequence showcase 

jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/util/compose_utils/showcase/ShowcaseStep.kt
Task: https://jira.devcats.kg/browse/MKK-11169
=> MKK-11169(fix): fix showcase background with edgeToEdge

app/src/main/java/kg/devcats/compose/samples/ui/chili_sample/PreviewCards.kt, jetpack_chili/src/main/java/kg/devcats/compose/jetpack_chili/components/cards/AdditionalContentInfoCard.kt
- Add optional clickable modifier
- Support clickable with or without ripple effect
=> BONUS-1995(feat): Add optional clickability to AdditionalContentInfoCard
